# Generated by Django 4.2 on 2023-06-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_pic', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('W', 'Женский'), ('M', 'Мужской')], max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
