# Generated by Django 4.2 on 2023-06-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_course_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_course_purchased',
            field=models.BooleanField(default=False, help_text='Отметьте, если курс был оплачен.', verbose_name='Оплата курса'),
        ),
    ]
