# Generated by Django 4.2 on 2023-06-06 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_text_remove_lesson_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.IntegerField(verbose_name='Разрешение видео')),
                ('file', models.FileField(upload_to='lessons/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Видео', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
