# Generated by Django 4.2 on 2023-06-25 13:17

import apps.courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=apps.courses.models.get_upload_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео'),
        ),
    ]
