# Generated by Django 4.2 on 2023-06-13 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(verbose_name='Ключ идемпотентности')),
                ('payment_id', models.CharField(max_length=100, verbose_name='ID платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('create_date', models.DateTimeField(verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
