# Generated by Django 4.2 on 2023-06-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmodel_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='check_file',
            field=models.FileField(blank=True, null=True, upload_to='checks', verbose_name='Файл чека'),
        ),
    ]
