# Generated by Django 4.2 on 2023-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentmodel_check_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='check_file',
            field=models.FileField(null=True, upload_to='checks/', verbose_name='Файл чека'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
