# Generated by Django 4.2 on 2023-06-19 02:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('text', models.TextField(help_text='не менее 20 символов', validators=[django.core.validators.MinLengthValidator(limit_value=20)], verbose_name='Сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback/', verbose_name='Файл')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pages.feedbackmodel', verbose_name='Отзыв')),
            ],
        ),
    ]
