# Generated by Django 4.2 on 2023-06-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'обращение', 'verbose_name_plural': 'обращения'},
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
    ]
