# Generated by Django 4.2 on 2023-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_feedbackmodel_options_feedbackmodel_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackfilemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Отметьте, если рассмотрение обращения закончено.', verbose_name='Закрыто'),
        ),
    ]
